#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BNC0D3.Resource", IsApplication=true)]

namespace BNC0D3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::BNC0D3.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::BNC0D3.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::BNC0D3.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::BNC0D3.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::BNC0D3.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::BNC0D3.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::BNC0D3.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::BNC0D3.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::BNC0D3.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::BNC0D3.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::BNC0D3.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::BNC0D3.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::BNC0D3.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::BNC0D3.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::BNC0D3.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::BNC0D3.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::BNC0D3.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::BNC0D3.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::BNC0D3.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::BNC0D3.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::BNC0D3.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::BNC0D3.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::BNC0D3.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::BNC0D3.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::BNC0D3.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::BNC0D3.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::BNC0D3.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::BNC0D3.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::BNC0D3.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::BNC0D3.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::BNC0D3.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::BNC0D3.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::BNC0D3.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::BNC0D3.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::BNC0D3.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::BNC0D3.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::BNC0D3.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Splat.Resource.String.library_name = global::BNC0D3.Resource.String.library_name;
			global::Vaquita4android.Resource.String.ApplicationName = global::BNC0D3.Resource.String.ApplicationName;
			global::Vaquita4android.Resource.String.Hello = global::BNC0D3.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int roundedbg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbgdark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int slider = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int slider1 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int calc_button = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int consoleIpt = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int consoleOpt = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int consoleSummit = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int content = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int def_button = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int exitbtn = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int gridView1 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int handle = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int horizontalScrollView1 = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int loadingImage = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int loadingProgressBar = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int loadingProgressWheel = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int optbtn = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int playbtn = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int scrollView1 = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int slidingDrawer1 = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView3 = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int textViewStatus = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int typeRadio = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int varName = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int varNumber = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int varString = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int varValue = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calcSetting = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int defSetting = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Launcher = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loading = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingimage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loadingprogress = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
